### ISSUE TITLE
Cant visualize bot

### ISSUE THREAD

**Issue by bornbygoogle** [OpenPoGo/OpenPoGoUI#23]
Hi, sorry for disturbing, but when i connect to openpogoui.nicontoso.eu I got only "Connecting to the bot ... ", and on terminal, i got "error: [Errno 32] Broken pipe", any idee ? Thanks a lot.

**Comment by niicojs** [comment]
I will need a little bit more information.
Like: OS, Browser, copy/paste of bot console log, copy/past of browser console log.

**Comment by bornbygoogle** [comment]
An example of console log : 

Exception in thread Thread-665:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in **bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.handle_error(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init**
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe

OS : Kali
Browser : Iceweasel

**Comment by niicojs** [comment]
Could you also share your browser log?

**Comment by bornbygoogle** [comment]
browser log ? what do you mean ??

**Comment by niicojs** [comment]
I don't know a thing about "Iceweasel" but there is usually a developer mode or a show console button somewhere. It is usually Ctrl+Shift+J or Ctrl+Shift+I.
